apiVersion: v1
kind: PersistentVolume
metadata:
  name: psql-pv-volume
  labels:
    app.kubernetes.io/name: postgresql
spec:
  storageClassName: ""
  capacity:
    storage: 8Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/bitnami/postgresql"

