- name: Initialise Kubeadm
#  shell: kubeadm init
  shell: kubeadm init --pod-network-cidr=10.244.0.0/16
  register: kube_token
- name: Create Home Kube folder
  file:
    path: /root/.kube
    state: directory
    owner: "{{ ansible_ssh_user }}"
    group: "{{ ansible_ssh_user }}"
- name: Copy config to Kube folder
  shell: cp /etc/kubernetes/admin.conf /root/.kube/config
- name: Apply Pod Network
#  shell: kubectl create -f https://raw.githubusercontent.com/projectcalico/calico/v3.24.1/manifests/tigera-operator.yaml
#  shell: kubectl apply -f https://docs.projectcalico.org/v3.8/manifests/calico.yaml
  shell: kubectl apply -f https://raw.githubusercontent.com/projectcalico/calico/v3.24.1/manifests/canal.yaml
- name: Generate join token
  shell: kubeadm token create --print-join-command
  register: kubeadm_join_cmd
  delegate_to: "{{ groups['master'][0] }}"
- name: setting kubeadmn join
  set_fact:
    kubeadm_join: "{{ kubeadm_join_cmd.stdout_lines[0] }}"
- name: display kubeadm join
  debug: 
    var: kubeadm_join
- name: Register master host with join token
  add_host:
    name: "melmore"
    kubeadm_join_node: "{{ kubeadm_join }}"
